# Imagen oficial de OpenJDK 17
FROM openjdk:17-jdk-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el .jar desde tu proyecto local
COPY EverGrowth-server/EverGrowth-server/target/EverGrowth-server-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto (Render asigna uno dinámico)
EXPOSE 8080

# Variables de entorno recomendadas
ENV JAVA_OPTS=""

# Comando para ejecutar la app usando el puerto asignado por Render
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -Dserver.port=${PORT:-8080} -jar app.jar"]